### ISSUE TITLE
Reference benchmark.js via JSPM or pass in as parameter to the constructor

### ISSUE THREAD

**Issue by zewa666** [aurelia/benchmarks#2]
I've seen that your App requires Benchmark.js manually in the index.html. The problem that results doing it this way is that the ES6 classes (like MicroTest) depend on a global Object. Now within your Test-UI thats no problem, but I was experimenting to implement a Console-UI with NodeJS, so I could automate the test process. Now that global object makes ones life pretty hard :)

For the sake of testing I just wen't with passing Benchmark as a parameter to the MicroTest constructor.

Below what I did so far:

```
// Preqreq
npm install es6-module-loader (could have alternatively also used the JSPM edition)
npm install request

* Modified app/performanceTest/microTest.js class constructor to accept Benchmark as 2nd parameter
constructor(name, Benchmark) {
  super(name);
  this.Benchmark = Benchmark;
   ...
}

// Code of console ui
var request = require('request');
// declare globally because Benchmark doesn't like JSPM :)
Benchmark = require('../lib/benchmark');
var System = require('es6-module-loader').System;
System.baseURL = "file:C:/aurelia/benchmarks/";
System.transpiler = 'babel';

request('http://localhost:8080/api/tests', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    var microTests = JSON.parse(body).micro;

    System.import('app/performanceTest/microTest').then(function (microTest) {
      microTests.forEach(function (tName) {
        var test = new microTest.MicroTest(tName, Benchmark);
        test.run().then(function (result) {
          console.log('Test "' + tName + '": ' + result._elapsed);
        });
      });
    });
  }
});
```

**Comment by OdeToCode** [comment]
I spent a few hours when I started this project trying to get Benchmark to work with jspm, there was always a problem where Benchmark was looking for the global Benchmark, right around here: : https://github.com/bestiejs/benchmark.js/blob/master/benchmark.js#L531

If you didn't have any issues, maybe something changed in jspm that allows this to work! I'll try it again.

**Comment by OdeToCode** [comment]
P.S. That's an awesome idea. Maybe it would nice to have a CLI for this.

**Comment by zewa666** [comment]
Yeah I thought maybe later we could add something like this into the Aurelia CLI. Downside is that it's only testing against V8 Engine but at least it's easier to automate.

**Comment by zewa666** [comment]
@OdeToCode ok you're right seems like Benchmark doesn't play nicely together with JSPM. Whatever, I changed the Node-Script to declare Benchmark globally as well. Not nice but at least it works that way

**Comment by EisenbergEffect** [comment]
Can we close this then?

**Comment by OdeToCode** [comment]
Closed for now. Think it will take a pull request to Benchmark to fix the issue.
